# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ctseassignment1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # --- Snyk Security Scan Step ---
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/docker@v1
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: docker.io/${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}
          args: --file=Dockerfile

  #     - name: Log in to container registry
  #       uses: docker/login-action@v2
  #       with:
  #         registry: https://index.docker.io/v1/
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Build and push container image to registry
  #       uses: docker/build-push-action@v3
  #       with:
  #         context: .
  #         push: true
  #         tags: index.docker.io/${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}
  #         file: ./Dockerfile

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: 'Production'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  #   steps:
  #     - name: Deploy to Azure Web App
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: 'ctseassignment1'
  #         slot-name: 'Production'
  #         publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
  #         images: 'index.docker.io/${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}'
