name: Snyk Security Scan Only

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/docker@v1
        continue-on-error: false  # Set to true if you don't want it to fail the workflow
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: docker.io/${{ secrets.DOCKER_USERNAME }}/myapp:test
          args: --file=Dockerfile
